# Introduction to PyTorch
## Tensors
### Check versions


In [1]:
import numpy as np
import torch
import sys
import matplotlib

# Check versions
print(f'Python version: {sys.version}')
print(f'Numpy version: {np.version.version}')
print(f'PyTorch version: {torch.version.__version__}')
print(f'Matplotlib version: {matplotlib.__version__}')
print(f'GPU present: {torch.cuda.is_available()}')

Python version: 3.9.5 (default, Oct 14 2021, 15:56:58) 
[GCC 10.3.0]
Numpy version: 1.20.3
PyTorch version: 1.10.0
Matplotlib version: 3.6.2
GPU present: True


### Tensors and their attributes

In [2]:
# Create simple tensor
a = torch.tensor([[1.0],[2],[3],[9]])
# a = torch.tensor([[1.0,2,3,9]])
# Some attributes
print('a: ', a)
print('Precision: ', a.dtype)
print('Device: ', a.device)
print('Shape: ', a.shape) # Returns tuple-like object of dimensions, also known as .size()
print('ndim: ', a.ndim)   # Number of dimensions, also known as .dim()
print('Requires grad: ', a.requires_grad)

a:  tensor([[1.],
        [2.],
        [3.],
        [9.]])
Precision:  torch.float32
Device:  cpu
Shape:  torch.Size([4, 1])
ndim:  2
Requires grad:  False


### Changing precision

In [7]:
a = torch.arange(10)
print('a.dtype: ', a.dtype)
print('-----------')
b = a.float()
c = a.double()
print('b.dtype: ', b.dtype)
print('c.dtype: ', c.dtype)
print('a.dtype: ', a.dtype)
# One can also use
d = a.to(torch.double)
print('-----------')
print('d.dtype: ', d.dtype)
print('a.dtype: ', a.dtype)

a.dtype:  torch.int64
-----------
b.dtype:  torch.float32
c.dtype:  torch.float64
a.dtype:  torch.int64
-----------
d.dtype:  torch.float64
a.dtype:  torch.int64


### Reshaping a tensor

In [6]:
# Reshape a tensor
a = torch.tensor([1,2,3,9])
b = a.view(2,-1) # Same as `a.view(2,2)`


b[0,0] = 10
print(b)
print(a)
print ('-----------')

c = torch.reshape(a, (2,-1))

c[0,0] = -1
print(c)
print(a)
# All these tensors points to the same memory adress.

tensor([[10,  2],
        [ 3,  9]])
tensor([10,  2,  3,  9])
-----------
tensor([[-1,  2],
        [ 3,  9]])
tensor([-1,  2,  3,  9])


In [6]:
a = torch.arange(6)
b = a.view(3,2)
print('b: ', b)

c = b.transpose(0,1) # Swap axes 0 and 1
print('c: ', c)

b:  tensor([[0, 1],
        [2, 3],
        [4, 5]])
c:  tensor([[0, 2, 4],
        [1, 3, 5]])


### Numpy/torch functions

In [7]:
a = torch.eye(3, dtype=torch.double) # Identity matrix
b = torch.zeros([3,2,9]) # Tensor initialized to zero with the specified dimension
c = torch.ones([3,2,9])  # Tensor initialized to zero with the specified dimension
d = torch.rand((2,1,3))  # Tensor with random numbers in the interval [0,1)
e = torch.linspace(0,3,101) # 101 equistant points in the interval [0,3]

### Indexing
Uses the usual convetions from Numpy

In [8]:
a = torch.arange(10).view(2,5)
print('a:\n', a)
print('\na[:, 1:3]:\n', a[:, 0:3])

a:
 tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

a[:, 1:3]:
 tensor([[0, 1, 2],
        [5, 6, 7]])


### Share data

In [9]:
x = np.linspace(0,1,101)
a = torch.from_numpy(x) # Convert numpy array to torch tensor
#print(a.dtype)

y = a.numpy() # Convert torch tensor to numpy array

z = x.copy()  # Copy the underlying memory
b = a.clone() # Copy the underlying memory

### Mathematical operations

In [10]:
x = torch.linspace(-1,1, 5)
print('x: ', x)
print('|x|: ', x.abs())
print('max(x): ', x.max())
print('x**2: ', x.pow(2))
print('||x||: ', x.pow(2).sum().sqrt())

x:  tensor([-1.0000, -0.5000,  0.0000,  0.5000,  1.0000])
|x|:  tensor([1.0000, 0.5000, 0.0000, 0.5000, 1.0000])
max(x):  tensor(1.)
x**2:  tensor([1.0000, 0.2500, 0.0000, 0.2500, 1.0000])
||x||:  tensor(1.5811)
